### PR TITLE
Feature/gwr 62 2

### PR DESCRIPTION
**Pull request by NickNish09**
# Description

- Add the other parts of contribution stats page

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Dangerous changes
- [ ] Chore (change that does not effect how the code works, eg: change color)
- [ ] Tests

## How to test

Put here all the things need to test this PR and verify your changes, also list any relevant details for tests (eg: have a wallet)

- Test A

### CODE REVIEW

**Comment by thaisribon** [comment]
on the ios simulator it is working fine but on my android phone if i click to see the contribution then go back and click again it is closing the app

**Comment by NickNish09** [comment]
> This heart below the text should be on top, right? Captura de Tela 2023-07-20 às 09 19 39

actually this is the cause name (it has an emoji). I can diminush the font size, but it would be different from figma. Idk if I should do that

**Comment by thaisribon** [comment]
> > This heart below the text should be on top, right? Captura de Tela 2023-07-20 às 09 19 39
> 
> actually this is the cause name (it has an emoji). I can diminush the font size, but it would be different from figma. Idk if I should do that

ah ok, no problem. I hadn't seen figma

**Comment by NickNish09** [comment]
> on the ios simulator it is working fine but on my android phone if i click to see the contribution then go back and click again it is closing the app

for some wierd reason this seems to be solved by changing the webview opacity:
[github issue thread](https://github.com/react-native-webview/react-native-webview/issues/811)

I left a comment in the code to avoid possible changes on this fix

**Review by thaisribon — APPROVED** [review]

**Pull request merged**
